### ISSUE TITLE
Educates/Workshops Deployment and Administration Documentation

### ISSUE THREAD

**Issue by jonasmit** [kube-academy/backlog#73]

**Comment by eitansuez** [comment]
I believe this story relates to this document which we drafted early in the week:
https://docs.google.com/document/u/1/d/16_ytfL50WCj2nSJ1eBfKsyK4obFWIbmivGzmi-pZWC4

I believe the document contains the information requested.  About to move this story to review.  Jon, if there is anything missing from the doc that should be documented, please let us know, otherwise, we can mark it done.  thanks, / eitan

**Comment by lxie123** [comment]
@lxie123 @djschny have been able to deploy and got permissions to esp

**Comment by djschny** [comment]
Closing this and making new issues for the lab author guide and for automation.
